CREATE TABLE users (   uid INT AUTO_INCREMENT PRIMARY KEY NOT NULL,   name VARCHAR(255) NOT NULL,   password VARCHAR(255) NOT NULL,   email VARCHAR(255) UNIQUE NOT NULL );

CREATE TABLE cards (     cid INT NOT NULL AUTO_INCREMENT,     uid INT,     question VARCHAR(255),     answer VARCHAR(255),     PRIMARY KEY (cid),     FOREIGN KEY (uid) REFERENCES
users(uid) ON UPDATE CASCADE ON DELETE CASCADE );
